steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'node-app-js asia-south1-docker.pkg.dev/niveus-gcp-training-1/shreyas-regisrty/node-app-js:v01', '.']
# images: ['us-west2-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello-world:latest']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello-world:latest']
# images: ['us-west2-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/hello-world:latest']
